

Starting Toontown Online...
Current time: Sat Dec 24 23:40:59 2022 Eastern Standard Time
sys.path =  ['', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python\\python27.zip', 'C:\\Panda3D-1.11.0-x64', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python\\DLLs', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python\\lib', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python\\lib\\plat-win', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python\\lib\\lib-tk', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\bin', 'C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\Panda3D-1.11.0-x64\\python\\lib\\site-packages']
sys.argv =  ['C:\\Toontown\\Toontown - Programming\\SuitopiaUpdateLastLaff\\Toontown-Last-Laff-Workspace\\src\\toontown\\launcher\\TTOffQuickStartLauncher.py']
generating standard configrc
os.environ =  {'TMP': 'C:\\Users\\theph\\AppData\\Local\\Temp', 'COMPUTERNAME': 'DESKTOP-7054VC9', 'PROCESSOR_LEVEL': '6', 'USERDOMAIN': 'DESKTOP-7054VC9', 'NEKO_INSTPATH': 'C:\\HaxeToolkit\\neko', 'INTEL_DEV_REDIST': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '9e0d', 'PATH': 'C:\\Panda3D-1.11.0-x64\\panda3d\\..\\bin;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Python38\\Scripts\\;C:\\Program Files\\Python38\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\dotnet\\;C:\\Users\\theph\\AppData\\Local\\Programs\\Python\\Python39;C:\\Users\\theph\\AppData\\Local\\Programs\\Python\\Python39\\Scripts;C:\\Program Files\\Common Files\\Autodesk Shared\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\HaxeToolkit\\haxe;C:\\HaxeToolkit\\neko;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Users\\theph\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\theph\\.dotnet\\tools;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2020.3.3\\bin;C:\\Users\\theph\\AppData\\Local\\atom\\bin;C:\\Users\\theph\\AppData\\Local\\GitHubDesktop\\bin;C:\\Panda3D-1.9.0-x64\\python;C:\\Panda3D-1.9.0-x64\\python\\Scripts;C:\\Panda3D-1.9.0-x64\\bin;C:\\Panda3D-1.9.0\\python;C:\\Panda3D-1.9.0\\python\\Scripts;C:\\Panda3D-1.9.0\\bin;C:\\Panda3D-1.10.0\\python;C:\\Panda3D-1.10.0\\python\\Scripts;C:\\Panda3D-1.10.0\\bin;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.2.2\\bin;;C:\\Users\\theph\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Panda3D-1.11.0\\python;C:\\Panda3D-1.11.0\\python\\Scripts;C:\\Panda3D-1.11.0\\bin;C:\\Users\\theph\\.dotnet\\tools;C:\\Panda3D-1.10.11-x64\\python;C:\\Panda3D-1.10.11-x64\\python\\Scripts;C:\\Panda3D-1.10.11-x64\\bin;C:\\Panda3D-1.11.0-x64\\python;C:\\Panda3D-1.11.0-x64\\python\\Scripts;C:\\Panda3D-1.11.0-x64\\bin;C:\\EventHorizon-battle-ng-teaser\\dependencies\\panda\\python;C:\\EventHorizon-battle-ng-teaser\\dependencies\\panda\\python\\Scripts;C:\\EventHorizon-battle-ng-teaser\\depe', 'SYSTEMROOT': 'C:\\WINDOWS', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'PPYTHON_PATH': '"Panda3D-1.11.0-x64\\python\\ppython.exe"', 'TEMP': 'C:\\Users\\theph\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'USERPROFILE': 'C:\\Users\\theph', 'LOCALAPPDATA': 'C:\\Users\\theph\\AppData\\Local', 'HOMEPATH': '\\Users\\theph', 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-7054VC9', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'theph', 'LOGONSERVER': '\\\\DESKTOP-7054VC9', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'ONEDRIVE': 'C:\\Users\\theph\\OneDrive', 'ADSK_3DSMAX_X64_2019': 'C:\\Program Files\\Autodesk\\3ds Max 2019\\', 'ZES_ENABLE_SYSMAN': '1', 'HAXEPATH': 'C:\\HaxeToolkit\\haxe', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'TTOFF_LOGIN_TOKEN': 'dev', 'WINDIR': 'C:\\WINDOWS', 'PYCHARM COMMUNITY EDITION': 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.2.2\\bin;', 'HOMEDRIVE': 'C:', 'SYSTEMDRIVE': 'C:', 'PUBLIC': 'C:\\Users\\Public', 'NUMBER_OF_PROCESSORS': '16', 'APPDATA': 'C:\\Users\\theph\\AppData\\Roaming', 'IDK2': 'C:\\Program Files\\Python38', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'ADSK_CLM_WPAD_PROXY_CHECK': 'FALSE', 'IDK': 'C:\\Program Files\\Python38\\Scripts'}
:12-24-2022 23:40:59 TTOffLauncher: isTestServer: 0
:12-24-2022 23:40:59 TTOffLauncher: Game Server 127.0.0.1
:12-24-2022 23:40:59 TTOffLauncher: Starting Toontown Online... 
:12-24-2022 23:40:59 TTOffLauncher: foreground: Launcher now operating in foreground
useTTOffSpecificLogin=True
:12-24-2022 23:40:59 TTOffLauncher: maybeStartGame: starting game
:12-24-2022 23:40:59 TTOffLauncher: Starting Toontown Online...
:12-24-2022 23:40:59 TTOffLauncher: background: Launcher now operating in background
ToontownStart: Polling for game2 to finish...
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
:12-24-2022 23:40:59 TTOffLauncher: setting panda error code to 7
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:12-24-2022 23:41:00 ToonBase: Default graphics pipe is wglGraphicsPipe (OpenGL).
:12-24-2022 23:41:00 :display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=24 color_bits=3 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 multisamples=70 back_buffers=1 force_hardware 
  got: depth_bits=24 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 accum_bits=64 multisamples=16 back_buffers=1 force_hardware 
:12-24-2022 23:41:00 ToonBase: Successfully opened window of type wglGraphicsWindow (OpenGL)
:12-24-2022 23:41:00 ShowBase: __dev__ == False
:12-24-2022 23:41:00 TTOffLauncher: setting panda error code to 11
:12-24-2022 23:41:00 TTOffLauncher: setting panda error code to 0
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  tto-dev
:12-24-2022 23:41:01 Loader: starting bulk load of block 'init'
:12-24-2022 23:41:07 :nativenet(error): Buffered_DatagramConnection Constructor rbufsize = 4096000 wbufsize = 4096000 write_flush_point = 1400
:12-24-2022 23:41:07 OTPClientRepository: Using connect method 'http'
:12-24-2022 23:41:12 TTOffLauncher: getRegistry ('DEPLOYMENT', None)
:12-24-2022 23:41:12 TTOffLauncher: checking env
:12-24-2022 23:41:12 TTOffLauncher: getRegistry ('GAME_DEPLOYMENT', None)
:12-24-2022 23:41:12 TTOffLauncher: checking env
:12-24-2022 23:41:12 OTPClientRepository: reg_deployment=
:12-24-2022 23:41:12 OTPClientRepository: required-login auto.
:12-24-2022 23:41:12 OTPClientRepository: loginInterface: LoginTTOffAccount
:12-24-2022 23:41:12 TTOffLauncher: getNeedPwForSecretKey using ttoff-specific-login
:12-24-2022 23:41:12 Loader: At end of block 'init', expected 138, loaded 14, duration=11.5440643
:12-24-2022 23:41:12 OTPClientRepository: Connecting to gameserver directly (no proxy).
:12-24-2022 23:41:12 OTPClientRepository: Connecting to //127.0.0.1:7198 via HTTP interface.
:12-24-2022 23:41:12 TTOffLauncher: Stopping mini task manager.
:12-24-2022 23:41:12 OTPClientRepository: Successfully connected to //127.0.0.1:7198.
:12-24-2022 23:41:12 TTOffLauncher: Setting Disconnect Details normal
{402000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x000000004474FA08>}
:12-24-2022 23:41:13 StateData: AvatarChooser.enter
:12-24-2022 23:41:13 DisplayOptions: settingsFullScreen = False, embedded = False width=800 height=600
:12-24-2022 23:41:13 StateData: calling self.displayOptions.restrictToEmbedded(False)
:12-24-2022 23:41:22 OTPClientRepository: ================
:12-24-2022 23:41:22 OTPClientRepository: Chose avatar id: 100000001
:12-24-2022 23:41:22 OTPClientRepository: Chose avatar name: Prof. Alvin Flippenhopper
:12-24-2022 23:41:22 OTPClientRepository: Chose avatar dna: ('dls', 'ss', 's', 'm', 15, 0, 15, 15, 1, 8, 1, 8, 1, 1)
:12-24-2022 23:41:22 OTPClientRepository: Chose avatar position: 1
:12-24-2022 23:41:22 OTPClientRepository: isPaid: 1
:12-24-2022 23:41:22 OTPClientRepository: freeTimeLeft: 0
:12-24-2022 23:41:22 OTPClientRepository: allowSecretChat: True
:12-24-2022 23:41:22 OTPClientRepository: ================
:12-24-2022 23:41:22 Loader: starting bulk load of block 'localAvatarPlayGame'
:12-24-2022 23:41:23 ToontownTimeManager(warning): error parsing date string=
local
:12-24-2022 23:41:24 NewsPageButtonManager(warning): Should not get here. NewsPageButtonManager.exitOff
:12-24-2022 23:41:24 :pnmimage:png(warning): iCCP: known incorrect sRGB profile
:12-24-2022 23:41:27 OTPClientRepository: Entering shard 402000001
:12-24-2022 23:41:27 StreetSign: Street sign url is https://ttoffline.com/images/
:12-24-2022 23:41:28 TimeManager: Clock sync: TimeManager.announceGenerate
:12-24-2022 23:41:28 NewsManager: setHolidayId: Starting Holiday 19
:12-24-2022 23:41:28 InGameNewsMgr: latestIssue=2013-08-22 16:49:46.000003-07:00
cpu info: GenuineIntel|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz|591597|0|3.600,3.600|8,16 cpus
:12-24-2022 23:41:31 OTPClientRepository: No sync from TimeManager.
:12-24-2022 23:41:31 OTPClientRepository: gotTimeSync
:12-24-2022 23:41:31 Loader: At end of block 'localAvatarPlayGame', expected 400, loaded 24, duration=8.1403243
:12-24-2022 23:41:31 TimeManager: Clock sync roundtrip took 2098.799 ms
:12-24-2022 23:41:31 TimeManager: AI time delta is -0:02 from server delta
:12-24-2022 23:41:31 TimeManager: Local clock uncertainty +/- 1.050 s
:12-24-2022 23:41:31 TimeManager: Uncertainty is too high, trying again.
:12-24-2022 23:41:31 PlayGame: QA-REGRESSION: NEIGHBORHOODS: Visit The Brrrgh
:12-24-2022 23:41:31 Loader: starting bulk load of block 'hood'
:12-24-2022 23:41:33 OTPClientRepository: Sending heartbeat mid-frame.
:12-24-2022 23:41:35 TimeManager: Clock sync roundtrip took 4491.328 ms
:12-24-2022 23:41:35 TimeManager: AI time delta is -0:04 from server delta
:12-24-2022 23:41:35 ClockDelta: previous delta at -4612.296 s, +/- 1.051 s.
:12-24-2022 23:41:35 ClockDelta: new delta at -4611.100 s, +/- 2.246 s.
:12-24-2022 23:41:35 ClockDelta: intersection at -4612.295 s, +/- 1.050 s.
:12-24-2022 23:41:35 TimeManager: Local clock uncertainty +/- 1.051 s
:12-24-2022 23:41:35 TimeManager: Uncertainty is too high, trying again.
:12-24-2022 23:41:35 DistributedObject(warning): no loader.getInteractiveProp self.interactiveProp is None
:12-24-2022 23:41:36 DistributedToon: calling LocalAvatar.startchat
:12-24-2022 23:41:36 Loader: At end of block 'hood', expected 10, loaded 27, duration=5.6409317
:12-24-2022 23:41:36 TimeManager: Clock sync roundtrip took 1147.703 ms
:12-24-2022 23:41:36 TimeManager: AI time delta is -0:01 from server delta
:12-24-2022 23:41:36 ClockDelta: previous delta at -4612.295 s, +/- 1.051 s.
:12-24-2022 23:41:36 ClockDelta: new delta at -4612.757 s, +/- 0.574 s.
:12-24-2022 23:41:36 ClockDelta: intersection at -4612.757 s, +/- 0.574 s.
:12-24-2022 23:41:36 TimeManager: Local clock uncertainty +/- 0.574 s
:12-24-2022 23:41:38 Teleport(debug): teleportInDone: walk
:12-24-2022 23:41:46 Playground: Unloading Place (3000). Fsm in final
:12-24-2022 23:41:46 Loader: starting bulk load of block 'hood'
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:46 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:41:47 :pnmimage:png(warning): Interlace handling should be turned on when using png_read_image
:12-24-2022 23:41:47 TownLoader: skipping self.geom.flattenMedium
:12-24-2022 23:41:48 Loader: At end of block 'hood', expected 40, loaded 6, duration=1.4298168
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:41:48 DistributedSuit(warning): Suit 402012527 created before its suit planner, 402002574
:12-24-2022 23:41:48 DistributedSuit(warning): Suit 402012527 does not have a suit planner!  Expected SP doId 402002574.
:12-24-2022 23:41:48 DistributedSuit(warning): Suit 402012527 does not have a suit planner!  Expected SP doId 402002574.
:12-24-2022 23:41:48 DistributedSuit(warning): Suit 402012527 does not have a path!
:12-24-2022 23:41:48 DistributedObject: DistributedSuitPlanner 402002574: generating
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:41:54 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/ac.png
:12-24-2022 23:41:54 :gobj(error): Unable to find texture "phase_3/maps/hands/ac.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:41:58 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/dt.png
:12-24-2022 23:41:58 :gobj(error): Unable to find texture "phase_3/maps/hands/dt.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:41:59 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:41:59 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:42:03 Street: QA-REGRESSION: COGBATTLE: Enter Battle
Battle Event localtoon-battle-event-3
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:42:24 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/mb.png
:12-24-2022 23:42:24 :gobj(error): Unable to find texture "phase_3/maps/hands/mb.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:42:41 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:42:41 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:42:51 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:42:51 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:42:53 Street: QA-REGRESSION: COGBATTLE: Enter Battle
Battle Event localtoon-battle-event-9
:12-24-2022 23:42:53 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/ac.png
:12-24-2022 23:42:53 :gobj(error): Unable to find texture "phase_3/maps/hands/ac.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:43:03 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/mb.png
:12-24-2022 23:43:03 :gobj(error): Unable to find texture "phase_3/maps/hands/mb.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:43:22 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:43:22 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:43:41 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:43:41 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:43:45 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:43:45 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:44:23 OTPClientRepository: Sending heartbeat mid-frame.
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:44:51 Street: Unloading Place (None). Fsm in final
:12-24-2022 23:44:51 DistributedObject: DistributedSuitPlanner 402002574: disabling
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 TownBattleSuitPanel: Loading Suit Battle Panel!
:12-24-2022 23:44:51 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/dt.png
:12-24-2022 23:44:51 :gobj(error): Unable to find texture "phase_3/maps/hands/dt.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:44:51 ClassicFSM(warning): [DistributedSuitInterior]: no transition exists from WaitForAllToonsInside to ReservesJoining
:12-24-2022 23:44:53 ToontownChatManager: QA-REGRESSION: CHAT: Speedchat
Battle Event localtoon-battle-event-15
:12-24-2022 23:45:03 ToontownChatManager: QA-REGRESSION: CHAT: Speedchat Plus
:12-24-2022 23:45:08 TTOffMagicWordManager: Restocked 999 unites successfully!
:12-24-2022 23:45:09 ToontownChatManager: QA-REGRESSION: CHAT: Speedchat
:12-24-2022 23:46:02 GarbageCollect(warning): garbage found, reverting gc threshold
:12-24-2022 23:46:06 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/sd.png
:12-24-2022 23:46:06 :gobj(error): Unable to find texture "phase_3/maps/hands/sd.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:46:06 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/b.png
:12-24-2022 23:46:06 :gobj(error): Unable to find texture "phase_3/maps/hands/b.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:46:06 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/bw.png
:12-24-2022 23:46:06 :gobj(error): Unable to find texture "phase_3/maps/hands/bw.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:46:06 ClassicFSM(warning): [DistributedSuitInterior]: no transition exists from Resting to ReservesJoining
Battle Event localtoon-battle-event-20
frame rate: 141.5 fps|0.004d|3 avs||327|328||0x0000|0x0000|971.8MB|2572.9MB|32590.0MB|1925|nt.2.6.2|3.600,3.600|8,16 cpus|OpenGL
:12-24-2022 23:47:20 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/b.png
:12-24-2022 23:47:20 :gobj(error): Unable to find texture "phase_3/maps/hands/b.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:47:20 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/ac.png
:12-24-2022 23:47:20 :gobj(error): Unable to find texture "phase_3/maps/hands/ac.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:47:20 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/le.png
:12-24-2022 23:47:20 :gobj(error): Unable to find texture "phase_3/maps/hands/le.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:47:20 :gobj(error): Texture::read() - couldn't read: phase_3/maps/hands/b.png
:12-24-2022 23:47:20 :gobj(error): Unable to find texture "phase_3/maps/hands/b.png" on model-path /;/c/Toontown/Toontown - Programming/SuitopiaUpdateLastLaff/Toontown-Last-Laff-Workspace/src/toontown/launcher;/c/Panda3D-1.11.0-x64/etc/..;/c/Panda3D-1.11.0-x64/etc/../models
Assertion failed: other._error_type == ET_ok at line 395 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:47:20 ClassicFSM(warning): [DistributedSuitInterior]: no transition exists from Resting to ReservesJoining
Battle Event localtoon-battle-event-25
:12-24-2022 23:47:43 ToonBase: User closed main window.
:12-24-2022 23:47:43 TimeManager: Client disconnect reason 2.
:12-24-2022 23:47:43 SuitInterior: Unloading Place (3811). Fsm in elevatorOut
:12-24-2022 23:47:43 OTPClientRepository(warning): unclean exit, abandoning shard
ignoring InputState-forward
:12-24-2022 23:47:43 OTPClientRepository: sending clientLogout
Assertion failed: _error_type != ET_not_found at line 592 of panda/src/pgraph/nodePath.cxx
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "toontown\toonbase\ToonBase.py", line 187, in windowEvent
    OTPBase.OTPBase.windowEvent(self, win)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\ShowBase.py", line 2791, in windowEvent
    self.userExit()
  File "toontown\toonbase\ToonBase.py", line 422, in userExit
    self.cr.loginFSM.request('shutdown')
  File "C:\Panda3D-1.11.0-x64\direct\fsm\ClassicFSM.py", line 281, in request
    exitArgList)
  File "C:\Panda3D-1.11.0-x64\direct\fsm\ClassicFSM.py", line 227, in __transition
    self.__exitCurrent(exitArgList)
  File "C:\Panda3D-1.11.0-x64\direct\fsm\ClassicFSM.py", line 185, in __exitCurrent
    self.__currentState.exit(argList)
  File "C:\Panda3D-1.11.0-x64\direct\fsm\State.py", line 213, in exit
    self.__exitFunc(*argList)
  File "toontown\distributed\ToontownClientRepository.py", line 430, in exitPlayingGame
    base.localAvatar.deleteOrDelay()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObject.py", line 201, in deleteOrDelay
    self.disableAnnounceAndDelete()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObject.py", line 204, in disableAnnounceAndDelete
    self.disableAndAnnounce()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObject.py", line 230, in disableAndAnnounce
    self.disable()
  File "toontown\toon\LocalToon.py", line 256, in disable
    self.book.unload()
  File "toontown\shtiker\ShtikerBook.py", line 150, in unload
    page.unload()
  File "toontown\shtiker\SuitPage.py", line 240, in unload
    shadow.removeNode()
AssertionError: _error_type != ET_not_found at line 592 of panda/src/pgraph/nodePath.cxx
:12-24-2022 23:47:43 :task(error): Exception occurred in PythonTask eventManager
:12-24-2022 23:47:43 TTOffLauncher: setting panda error code to 12
:12-24-2022 23:47:43 TTOffLauncher(warning): Handling Python exception.
:12-24-2022 23:47:43 OTPClientRepository: Sent disconnect message to server
:12-24-2022 23:47:43 OTPClientRepository: Closing connection to server.
:12-24-2022 23:47:43 TTOffLauncher: Exception exit.

Traceback (most recent call last):
  File "otp\launcher\LauncherBase.py", line 1081, in mainLoop
    self._runTaskManager()
  File "otp\launcher\LauncherBase.py", line 1052, in _runTaskManager
    taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 528, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 482, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "toontown\toonbase\ToonBase.py", line 187, in windowEvent
    OTPBase.OTPBase.windowEvent(self, win)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\ShowBase.py", line 2791, in windowEvent
    self.userExit()
  File "toontown\toonbase\ToonBase.py", line 422, in userExit
    self.cr.loginFSM.request('shutdown')
  File "C:\Panda3D-1.11.0-x64\direct\fsm\ClassicFSM.py", line 281, in request
    exitArgList)
  File "C:\Panda3D-1.11.0-x64\direct\fsm\ClassicFSM.py", line 227, in __transition
    self.__exitCurrent(exitArgList)
  File "C:\Panda3D-1.11.0-x64\direct\fsm\ClassicFSM.py", line 185, in __exitCurrent
    self.__currentState.exit(argList)
  File "C:\Panda3D-1.11.0-x64\direct\fsm\State.py", line 213, in exit
    self.__exitFunc(*argList)
  File "toontown\distributed\ToontownClientRepository.py", line 430, in exitPlayingGame
    base.localAvatar.deleteOrDelay()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObject.py", line 201, in deleteOrDelay
    self.disableAnnounceAndDelete()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObject.py", line 204, in disableAnnounceAndDelete
    self.disableAndAnnounce()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObject.py", line 230, in disableAndAnnounce
    self.disable()
  File "toontown\toon\LocalToon.py", line 256, in disable
    self.book.unload()
  File "toontown\shtiker\ShtikerBook.py", line 150, in unload
    page.unload()
  File "toontown\shtiker\SuitPage.py", line 240, in unload
    shadow.removeNode()
AssertionError: _error_type != ET_not_found at line 592 of panda/src/pgraph/nodePath.cxx
